development:
  teachersets:
    #host: 'http://localhost:9200/'
    host: 'http://elasticsearch:9200'
    connect_timeout: 3
    index: 'teacherset'
    type: 'teacherset'
    teachersets_per_page: 10
    size: 10000

qa:
  teachersets:
    host: "AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKswgagGCSqGSIb3DQEHBqCBmjCBlwIBADCBkQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxmV/rQcH0PEpTP/e0CARCAZM7Y5WpMxizb+hPnVNlHDp2MNM12elMYOcy3n7I0ix+DxfB6EfVDQoSMDSPWSf/uVlaBq/yMdEzYS3ZGN/Zzd1SrmU7N9S5aUEretGu+9/5sPu2eXl/N+mBzYxMqt00oznAf0mk="
    connect_timeout: 3
    index: 'teacherset'
    type: 'teacherset'
    teachersets_per_page: 10
    size: 10000

production:
  teachersets:
    host: "AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAALMwgbAGCSqGSIb3DQEHBqCBojCBnwIBADCBmQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAz+uWwzu8aSQMbcufgCARCAbDerYV+KnsRNGPUtkRFBfynrgCR1i1h+Bx0XFJXvGMlfoqpuQh8PAWUNXjzpmoZhL2TQ9Eht+RIBIW7WlFG8jo1c0rdY4cfsA/wLdUE+VVIzb4WzX0rqS+lRjhMtyNuVJS/2YNWVmtYZAk4LJw=="
    connect_timeout: 3
    index: 'teacherset'
    type: 'teacherset'
    teachersets_per_page: 10
    size: 10000

test:
  teachersets:
    #host: "AQECAHjqALewp8JBJNxIQvR4oY795dyG7INaGR1glMsTEgetggAAALQwgbEGCSqGSIb3DQEHBqCBozCBoAIBADCBmgYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyS9HSNvErgrdg9VuwCARCAbZYtB/RGgKYco/pRRFwU2rC2P6CMfQs4ExV20e693vMOqQiBHalhLXLASQVJZkR8Izatvt9G3pdhB7RdWbFaUh1HBiwQemuRV0rUnM3bhhAYh7I2SVUJFVCG3a07zmDDBLeVtEW+KbVXv9Qw0E0="
    host: 'http://elasticsearch:9200'
    connect_timeout: 3
    index: 'teacherset'
    type: 'teacherset'
    teachersets_per_page: 10
    size: 10000
    
